// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57pzpepdH9yea7dAzAQMHAAS611PLNEc',
    appId: '1:423450762244:android:9580b3c89898bbda2c2951',
    messagingSenderId: '423450762244',
    projectId: 'rental-car-app-41d5a',
    storageBucket: 'rental-car-app-41d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7WPv94U0qUTD1lStJVWVPt-XdezhqR_A',
    appId: '1:423450762244:ios:8a968b93a9bd17402c2951',
    messagingSenderId: '423450762244',
    projectId: 'rental-car-app-41d5a',
    storageBucket: 'rental-car-app-41d5a.firebasestorage.app',
    iosBundleId: 'com.example.carsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWiTHILU52b2uHeZkOVJ-TFesTkbClbxE',
    appId: '1:423450762244:web:b680b78db005d6032c2951',
    messagingSenderId: '423450762244',
    projectId: 'rental-car-app-41d5a',
    authDomain: 'rental-car-app-41d5a.firebaseapp.com',
    storageBucket: 'rental-car-app-41d5a.firebasestorage.app',
    measurementId: 'G-G8ZPB3VB5L',
  );
}
